"""
Coverage aggregator: combine tier classification and fertility into a
per-language, per-model coverage result ready for JSON storage and the API.

Output schema (data/coverage/{safe_model_id}.json):
{
  "model_id":         "gpt-4",
  "source":           "tiktoken",
  "vocab_size":       100256,
  "has_byte_fallback": true,
  "computed_at":      "2026-05-12T10:00:00Z",
  "languages": {
    "hi": {
      "name":        "Hindi",
      "script":      "Deva",
      // Glottolog enrichment (when available)
      "glottocode":  "hin1269",
      "iso639_3":    "hin",
      "macroarea":   "Eurasia",
      "family_id":   "indo1319",
      "family_name": "Indo-European",
      "latitude":    25.0,
      "longitude":   77.0,
      "main": {
        "total":          68,
        "weighted_score": 0.8823,
        "tier0_count":    55,
        "tier1_count":    8,
        "tier2_count":    5,
        "tier3_count":    0,
        "tier1": [2366, 2367],   // code points at each degraded tier
        "tier2": [2385],
        "tier3": []
      },
      // Typology of the denominator behind "main.weighted_score".  The CLDR
      // exemplar set is the script's real inventory for alphabets/abjads/
      // abugidas, but a frequency sample for Han and a precomposed enumeration
      // for Hangul, so raw scores are not comparable across all scripts.
      "script_type":      "abugida",
      "denominator_kind": "closed_inventory",
      "comparability":    "direct",          // or "within_script_only"

      // Present only for combinatorial scripts (Hangul).  Scores the generator
      // set instead of the precomposed units — see script_types.py.
      "main_normalized": {
        "total": 67, "weighted_score": 0.97, ...,
        "normalization": "hangul_jamo",
        "note": "11172 precomposed Hangul syllables are generated by 67 ..."
      },

      "auxiliary": { ... },      // optional, only if exemplar data exists
      "fertility": {             // optional, only if --fertility flag used
        "tokens_per_char": 1.42,
        "tokens_per_word": 5.31,
        "sample_chars":    2847,
        "sample_tokens":   4041
      }
    },
    // Languages known from Glottolog but with no CLDR exemplar data:
    "aaa1241": {
      "name":       "Ghotuo",
      "glottocode": "aaa1241",
      "iso639_3":   "aaa",
      "macroarea":  "Africa",
      "family_id":  "atla1278",
      "family_name": "Atlantic-Congo",
      "has_cldr":   false        // no character-level analysis possible
    },
    ...
  }
}
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

from pipeline.tokenizers.base import ModelVocabData
from pipeline.analysis.tier_classifier import classify
from pipeline.analysis.fertility import compute_fertility
from pipeline.analysis.script_types import (
    comparability,
    denominator_kind,
    normalize_exemplars,
    script_type,
)
from pipeline.unicode.historic_scripts import scripts_all_unencoded

# Glottolog is optional — if the database hasn't been fetched yet we still
# produce a valid (unenriched) coverage result.
_GLOTTOLOG_CLDR_INDEX: dict[str, list[dict]] | None = None


def _get_glottolog_index() -> dict[str, list[dict]]:
    """
    Lazy-load a CLDR-locale → list[glottolog_entry] index.
    Returns an empty dict if Glottolog data hasn't been fetched.
    """
    global _GLOTTOLOG_CLDR_INDEX
    if _GLOTTOLOG_CLDR_INDEX is not None:
        return _GLOTTOLOG_CLDR_INDEX

    try:
        from pipeline.unicode.glottolog_loader import (
            load_languoid_database,
            cldr_to_glottolog_index,
        )
        languoids = load_languoid_database()
        raw_index = cldr_to_glottolog_index(languoids)
        # Expand: locale → list of full entry dicts
        _GLOTTOLOG_CLDR_INDEX = {
            locale: [languoids[gc] for gc in glottocodes if gc in languoids]
            for locale, glottocodes in raw_index.items()
        }
    except FileNotFoundError:
        _GLOTTOLOG_CLDR_INDEX = {}

    return _GLOTTOLOG_CLDR_INDEX

_ROOT = Path(__file__).parents[2]
_DATA_DIR = _ROOT / "data"


# ---------------------------------------------------------------------------
# Core computation
# ---------------------------------------------------------------------------

def compute_coverage(
    vocab: ModelVocabData,
    language_db: dict[str, dict],
    tokenize_fn: Callable[[str], list[int]] | None = None,
    include_glottolog_stubs: bool = True,
) -> dict:
    """
    Compute tier-based coverage for `vocab` against every language in
    `language_db`, enriched with Glottolog metadata where available.

    Args:
        vocab:                   Extracted vocabulary data for a model.
        language_db:             CLDR language database as returned by cldr_loader.
        tokenize_fn:             Optional callable for fertility scoring.
                                 Signature: (text: str) -> list[int]
                                 If None, fertility metrics are omitted.
        include_glottolog_stubs: If True and the Glottolog database has been
                                 fetched, append stub entries for Glottolog
                                 languages that have no CLDR exemplar data.
                                 These entries carry metadata only (no tier
                                 analysis) and have has_cldr=False.

    Returns:
        A dict suitable for JSON serialisation (see module docstring).
    """
    glottolog_index = _get_glottolog_index()
    languages: dict[str, dict] = {}

    # ------------------------------------------------------------------
    # Languages with CLDR exemplar data → full tier analysis
    # ------------------------------------------------------------------
    for locale_id, lang_data in language_db.items():
        exemplar_main = set(lang_data.get("exemplar_main", []))
        exemplar_aux  = set(lang_data.get("exemplar_auxiliary", []))

        if not exemplar_main:
            continue

        script = lang_data.get("script", "")
        main_result = classify(exemplar_main, vocab)
        entry: dict = {
            "name":     lang_data.get("name", locale_id),
            "script":   script,
            "has_cldr": lang_data.get("has_cldr", True),
            "main":     main_result.to_dict(),
            # How the exemplar denominator relates to the script's real
            # inventory, and therefore how the score above may be read.
            # See pipeline/analysis/script_types.py.
            "script_type":       script_type(script),
            "denominator_kind":  denominator_kind(script),
            "comparability":     comparability(script),
        }

        # Synthetic exemplars (e.g. Unicode-block sets for extinct scripts)
        # carry their own provenance and metadata; surface them without
        # pretending the numbers came from CLDR.
        if lang_data.get("exemplar_source"):
            entry["exemplar_source"] = lang_data["exemplar_source"]
        for _k in ("glottocode", "iso639_3", "macroarea", "family_id",
                   "family_name", "latitude", "longitude", "is_historical",
                   "language_type"):
            if lang_data.get(_k) is not None and _k not in entry:
                entry[_k] = lang_data[_k]

        # Combinatorial scripts get a second score against their generator set.
        # Korean is the case that matters: 11,172 precomposed syllables vs 67
        # Jamo that compose all of them.
        norm = normalize_exemplars(script, exemplar_main)
        if norm is not None:
            entry["main_normalized"] = {
                **classify(norm.codepoints, vocab).to_dict(),
                "normalization": norm.kind,
                "note":          norm.note,
            }

        if exemplar_aux:
            entry["auxiliary"] = classify(exemplar_aux, vocab).to_dict()

        if tokenize_fn is not None:
            # Pass the script so multi-script locales measure fertility on the
            # same writing system the tier scores above were computed for.
            fertility = compute_fertility(
                locale_id, tokenize_fn, script=lang_data.get("script") or None
            )
            if fertility is not None:
                entry["fertility"] = fertility

        # Enrich with Glottolog metadata (use first matching entry)
        glottolog_entries = glottolog_index.get(locale_id, [])
        if glottolog_entries:
            gl = glottolog_entries[0]
            entry.update({
                "glottocode":  gl["glottocode"],
                "iso639_3":    gl["iso639_3"],
                "macroarea":   gl["macroarea"],
                "family_id":   gl["family_id"],
                "family_name": gl["family_name"],
                "latitude":    gl["latitude"],
                "longitude":   gl["longitude"],
                "is_historical": gl.get("is_historical"),
                "language_type": gl.get("language_type"),
            })

        languages[locale_id] = entry

    # ------------------------------------------------------------------
    # Glottolog-only languages → metadata stubs (no tier analysis)
    # ------------------------------------------------------------------
    if include_glottolog_stubs and glottolog_index:
        try:
            from pipeline.unicode.glottolog_loader import load_languoid_database
            all_languoids = load_languoid_database()
        except FileNotFoundError:
            all_languoids = {}

        cldr_locales_covered = set(language_db.keys())

        # GlotScript-R gives us the writing system for ~7,000 ISO 639-3 codes.
        # It does NOT give us exemplar characters, so it cannot make a language
        # scoreable — a stub stays a stub.  What it adds is the script, which
        # supports the coarser claim "this tokenizer has no codepoints for the
        # script this language is written in".  See glotscript_loader for why
        # that distinction is kept strict.
        try:
            from pipeline.unicode.glotscript_loader import (
                load_glotscript,
                orthographic_main as _orthographic_main,
            )
            glotscript = load_glotscript()
        except Exception:
            glotscript = {}
            def _orthographic_main(_iso):  # noqa: E306 — degrade to no script info
                return []

        # Wikidata fills script gaps GlotScript leaves open (cached; empty if
        # never fetched).  Used only as a fallback when GlotScript is silent.
        try:
            from pipeline.unicode.wikidata_scripts import load_wikidata_scripts
            wikidata_scripts = load_wikidata_scripts()
        except Exception:
            wikidata_scripts = {}

        # Which scripts does this tokenizer represent at all?  Derived from the
        # scored languages, whose exemplar characters we do have.
        scripts_present: set[str] = set()
        # Scripts we have any evidence about at all.  A script outside this set
        # was never scored, so we cannot say whether the tokenizer covers it and
        # must report None rather than guessing False.
        scripts_observed: set[str] = set()
        for entry in languages.values():
            scr = entry.get("script")
            main = entry.get("main") or {}
            if not scr or not main.get("total"):
                continue
            scripts_observed.add(scr)
            # "Represented" means the tokenizer resolves characters of this
            # script at all.  Tier 0 is the BEST tier (native single token) and
            # tier 3 is unreachable — see tier_classifier for the ladder — so a
            # script counts as represented when any scored language in it has a
            # non-zero weighted score, i.e. at least some characters land above
            # tier 3.  Using a score rather than a tier count keeps this correct
            # if the tier ladder is ever extended.
            if (main.get("weighted_score") or 0) > 0:
                scripts_present.add(scr)

        for glottocode, gl in all_languoids.items():
            cldr_locale = gl.get("cldr_locale")
            # Only add as stub if this language isn't already in the results
            if cldr_locale and cldr_locale in cldr_locales_covered:
                continue
            if gl.get("has_cldr"):
                continue  # Should have been covered above; skip duplicates.
            # A historical language may already be present as a scored entry
            # keyed by glottocode (synthetic Unicode-block exemplar); never let
            # the stub overwrite that real analysis.
            if glottocode in languages:
                continue

            # Writing system from GlotScript, where the language has an ISO
            # 639-3 code to join on.  Glottolog assigns no ISO code to ~740
            # languoids, which are therefore unreachable by this route.
            gs = glotscript.get(gl["iso639_3"]) if gl.get("iso639_3") else None
            # The full orthographic set, never a single collapsed "the" script:
            # GlotScript's main column is unordered, so element zero is Braille
            # for English and Hindi.  See glotscript_loader for the detail.
            scripts = _orthographic_main(gl["iso639_3"]) if gl.get("iso639_3") else []
            # Fall back to Wikidata for languages GlotScript has no script for.
            script_source = "glotscript" if scripts else None
            if not scripts and gl.get("iso639_3"):
                wd = wikidata_scripts.get(gl["iso639_3"], [])
                if wd:
                    scripts = wd
                    script_source = "wikidata"

            # Reachability is three-valued.  None means "cannot tell": either no
            # script is known, or none of this language's scripts appears among
            # the ones we actually scored.  It must not be read as "no".
            testable = [s for s in scripts if s in scripts_observed]
            if not testable:
                script_supported = None
            else:
                # Written in *any* represented script is enough — a digraphic
                # language is reachable if either orthography is covered.
                script_supported = any(s in scripts_present for s in testable)

            # A script Unicode does not encode is unreachable by construction:
            # no tokenizer can hold code points that do not exist.  This is a
            # stronger, source-independent verdict than the tokenizer-derived
            # one above, so it overrides it.
            if scripts and scripts_all_unencoded(scripts):
                script_supported = False
                script_encoded = False
            else:
                script_encoded = None

            # Use glottocode as the key for stub entries
            languages[glottocode] = {
                "name":        gl["name"],
                "glottocode":  gl["glottocode"],
                "iso639_3":    gl["iso639_3"],
                "cldr_locale": cldr_locale,
                "macroarea":   gl["macroarea"],
                "family_id":   gl["family_id"],
                "family_name": gl["family_name"],
                "latitude":    gl["latitude"],
                "longitude":   gl["longitude"],
                "has_cldr":    False,
                # Temporal classification (ISO 639-3), so a historical language
                # with no script data is distinguishable from a living one we
                # simply have not scored.
                "is_historical": gl.get("is_historical"),
                "language_type": gl.get("language_type"),
                # --- GlotScript-derived, script level only ---
                # A list, because 603 languages are attested in more than one
                # script and there is no field marking which is primary.
                "scripts":           scripts,
                "script_aux":        (gs["aux"] if gs else []) or [],
                "script_source":     script_source,
                "unwritten":         bool(gs["unwritten"]) if gs else None,
                # True/False/None — see above; NOT a coverage score.
                "script_supported":  script_supported,
                # False when the script has no Unicode encoding at all; None
                # when encoding is not the limiting factor.
                "script_encoded":    script_encoded,
                # Explicit: this language has no character-level analysis.
                "scored":            False,
            }

    return {
        "model_id":          vocab.model_id,
        "source":            vocab.source,
        "vocab_size":        vocab.vocab_size,
        "has_byte_fallback": vocab.has_byte_fallback,
        "computed_at":       datetime.now(timezone.utc).isoformat(),
        "languages":         languages,
    }


# ---------------------------------------------------------------------------
# Storage helpers
# ---------------------------------------------------------------------------

def _safe_model_id(model_id: str) -> str:
    """Convert a model ID to a filesystem-safe filename stem."""
    return model_id.replace("/", "__").replace(":", "_").replace(" ", "_")


def save_coverage(result: dict, out_dir: Path | None = None) -> Path:
    """Serialise a coverage result to disk. Returns the written path."""
    if out_dir is None:
        out_dir = _DATA_DIR / "coverage"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_safe_model_id(result['model_id'])}.json"
    out_path.write_text(
        json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return out_path


def save_vocab(vocab: ModelVocabData, out_dir: Path | None = None) -> Path:
    """Serialise extracted vocabulary data to disk. Returns the written path."""
    if out_dir is None:
        out_dir = _DATA_DIR / "models"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{_safe_model_id(vocab.model_id)}.json"
    out_path.write_text(
        json.dumps(vocab.to_json_dict(), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return out_path


def load_coverage(model_id: str, data_dir: Path | None = None) -> dict | None:
    """Load a previously computed coverage result, or None if not found."""
    if data_dir is None:
        data_dir = _DATA_DIR / "coverage"
    path = data_dir / f"{_safe_model_id(model_id)}.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None
