"""
Script typology and score comparability.

Why this module exists
----------------------
loove's headline metric divides a weighted tier sum by the size of the language's
CLDR exemplar set. That denominator is not a neutral quantity: it reflects how
CLDR chose to enumerate a writing system, and that choice varies by three orders
of magnitude across scripts.

    script  median exemplar set
    Kore              11172      precomposed Hangul syllables
    Hant               2470      Han ideographs (frequency sample)
    Jpan               2311      kana + Han
    Ethi                295      syllabic Ethiopic
    Deva                 65      consonants + vowel signs
    Latn                 28      letters

Across the 310 languages in the database, the correlation between log10 exemplar
set size and mean weighted score is r = -0.60. Roughly a third of the variance in
loove's headline number is explained by the denominator alone, before any
property of the tokenizer is considered. Korean is the extreme case: its mean
score across ingested models is 0.15, the lowest of any major language, because
its denominator is all 11,172 precomposed Hangul syllable blocks. The same text
is generated from 67 Jamo, and a model holding those 67 can compose every
syllable — yet under the raw metric it scores near zero.

Cross-script leaderboards built on the raw score therefore rank scripts, not
tokenizers. This module classifies each script so that consumers can say which
comparisons are legitimate, and supplies a principled normalization where one
exists.

Denominator kinds
-----------------
``closed_inventory``
    The exemplar set is approximately the script's actual character inventory:
    alphabets, abjads, and abugidas. Scores are directly comparable to each
    other.

``combinatorial``
    The exemplar set enumerates precomposed units generated by a smaller set of
    components — Hangul syllable blocks from Jamo. A normalized score against
    the generator set is well defined, so both are reported.

``open_set``
    The exemplar set is a frequency-based sample of an open-ended repertoire
    (Han ideographs). There is no canonical denominator: the number is a
    property of CLDR's cut-off, not of the script. Comparable only against the
    same script.

``syllabic_derived``
    A closed but combinatorially generated syllabary (Ethiopic, Vai, Cherokee,
    Canadian Aboriginal). Inventories are large relative to alphabets, and CLDR
    lists surface syllables. Treated as within-script-comparable rather than
    normalized, since the component decomposition is not uniformly expressible
    in Unicode.
"""
from __future__ import annotations

import unicodedata
from dataclasses import dataclass

# ---------------------------------------------------------------------------
# Script classification
# ---------------------------------------------------------------------------

#: ISO 15924 script code → (script_type, denominator_kind)
SCRIPT_TYPES: dict[str, tuple[str, str]] = {
    # Alphabets — one code point per phoneme, small closed inventory
    "Latn": ("alphabet", "closed_inventory"),
    "Cyrl": ("alphabet", "closed_inventory"),
    "Grek": ("alphabet", "closed_inventory"),
    "Armn": ("alphabet", "closed_inventory"),
    "Geor": ("alphabet", "closed_inventory"),
    "Copt": ("alphabet", "closed_inventory"),
    "Runr": ("alphabet", "closed_inventory"),
    "Ogam": ("alphabet", "closed_inventory"),
    "Osge": ("alphabet", "closed_inventory"),
    "Olck": ("alphabet", "closed_inventory"),
    "Tfng": ("alphabet", "closed_inventory"),
    "Nkoo": ("alphabet", "closed_inventory"),
    "Adlm": ("alphabet", "closed_inventory"),
    "Hmnp": ("alphabet", "closed_inventory"),
    "Dsrt": ("alphabet", "closed_inventory"),
    "Shaw": ("alphabet", "closed_inventory"),
    "Vaii": ("syllabary", "syllabic_derived"),
    # Abjads — consonantal, vowels optional
    "Arab": ("abjad", "closed_inventory"),
    "Hebr": ("abjad", "closed_inventory"),
    "Syrc": ("abjad", "closed_inventory"),
    "Thaa": ("abjad", "closed_inventory"),
    "Samr": ("abjad", "closed_inventory"),
    "Rohg": ("abjad", "closed_inventory"),
    # Abugidas — consonant base plus vowel diacritics
    "Deva": ("abugida", "closed_inventory"),
    "Beng": ("abugida", "closed_inventory"),
    "Guru": ("abugida", "closed_inventory"),
    "Gujr": ("abugida", "closed_inventory"),
    "Orya": ("abugida", "closed_inventory"),
    "Taml": ("abugida", "closed_inventory"),
    "Telu": ("abugida", "closed_inventory"),
    "Knda": ("abugida", "closed_inventory"),
    "Mlym": ("abugida", "closed_inventory"),
    "Sinh": ("abugida", "closed_inventory"),
    "Thai": ("abugida", "closed_inventory"),
    "Laoo": ("abugida", "closed_inventory"),
    "Tibt": ("abugida", "closed_inventory"),
    "Mymr": ("abugida", "closed_inventory"),
    "Khmr": ("abugida", "closed_inventory"),
    "Java": ("abugida", "closed_inventory"),
    "Bali": ("abugida", "closed_inventory"),
    "Tglg": ("abugida", "closed_inventory"),
    "Cakm": ("abugida", "closed_inventory"),
    "Tavt": ("abugida", "closed_inventory"),
    "Talu": ("abugida", "closed_inventory"),
    "Lana": ("abugida", "closed_inventory"),
    "Mtei": ("abugida", "closed_inventory"),
    "Saur": ("abugida", "closed_inventory"),
    "Tale": ("abugida", "closed_inventory"),
    # Syllabaries — surface syllables enumerated, large inventories
    "Ethi": ("syllabary", "syllabic_derived"),
    "Cher": ("syllabary", "syllabic_derived"),
    "Cans": ("syllabary", "syllabic_derived"),
    "Yiii": ("syllabary", "syllabic_derived"),
    "Bamu": ("syllabary", "syllabic_derived"),
    # Featural syllabary — precomposed blocks generated from Jamo
    "Kore": ("featural_syllabary", "combinatorial"),
    "Hang": ("featural_syllabary", "combinatorial"),
    # Logographic / mixed — open-ended repertoire, exemplars are a frequency cut
    "Hans": ("logographic", "open_set"),
    "Hant": ("logographic", "open_set"),
    "Hani": ("logographic", "open_set"),
    "Jpan": ("mixed_logographic", "open_set"),
    "Hira": ("syllabary", "closed_inventory"),
    "Kana": ("syllabary", "closed_inventory"),
    "Nshu": ("logographic", "open_set"),
    "Egyp": ("logographic", "open_set"),
    "Xsux": ("logographic", "open_set"),
}

#: Denominator kinds whose raw scores may be compared across scripts.
DIRECTLY_COMPARABLE = {"closed_inventory"}

_UNKNOWN = ("unknown", "closed_inventory")


def script_type(script: str) -> str:
    """Return the typological class of an ISO 15924 script code."""
    return SCRIPT_TYPES.get(script, _UNKNOWN)[0]


def denominator_kind(script: str) -> str:
    """
    Return how the CLDR exemplar set for this script relates to the script's
    real character inventory. See the module docstring for the four values.
    """
    return SCRIPT_TYPES.get(script, _UNKNOWN)[1]


def is_comparable(script: str) -> bool:
    """
    True when a raw weighted score for this script can be placed on the same
    axis as scores for other scripts.
    """
    return denominator_kind(script) in DIRECTLY_COMPARABLE


def comparability(script: str) -> str:
    """``"direct"`` or ``"within_script_only"`` — how this score may be read."""
    return "direct" if is_comparable(script) else "within_script_only"


# ---------------------------------------------------------------------------
# Normalization for combinatorial scripts
# ---------------------------------------------------------------------------

@dataclass
class Normalization:
    """
    A principled alternative denominator for a combinatorial script.

    Attributes:
        codepoints: The generator set — the components a model needs in order to
            compose every unit in the original exemplar set.
        kind:       Identifier for the decomposition applied.
        note:       Human-readable justification, surfaced in the dashboard.
    """

    codepoints: set[int]
    kind: str
    note: str


def normalize_exemplars(script: str, codepoints: set[int]) -> Normalization | None:
    """
    Return a generator-set normalization for ``codepoints``, or None when no
    principled one exists for this script.

    Only ``combinatorial`` scripts are normalizable. Hangul syllable blocks
    (U+AC00–U+D7A3) decompose canonically to conjoining Jamo under NFD, so the
    generator set is well defined and small. Han ideographs do not decompose to
    a closed component set in Unicode, and syllabic scripts such as Ethiopic
    have no uniform canonical decomposition, so both return None.
    """
    if denominator_kind(script) != "combinatorial":
        return None

    jamo: set[int] = set()
    passthrough: set[int] = set()
    for cp in codepoints:
        decomposed = unicodedata.normalize("NFD", chr(cp))
        if len(decomposed) > 1:
            jamo.update(ord(ch) for ch in decomposed)
        else:
            passthrough.add(cp)

    if not jamo:
        return None

    return Normalization(
        codepoints=jamo | passthrough,
        kind="hangul_jamo",
        note=(
            f"{len(codepoints)} precomposed Hangul syllables are generated by "
            f"{len(jamo)} conjoining Jamo; scoring against the Jamo measures "
            "whether the model can compose Korean rather than whether it "
            "memorised every syllable block."
        ),
    )
